name: CI

on:
  push:
  schedule:
  # - cron: 0 10-20 * * 1-5 # every hour in working hour of working day
  - cron: 0 6 1 * * # every Month at 1st

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
         ref: master
    - name: Install cake
      run: make install_cake
    - name: Install
      run: cake update
    - name: Save
      run: make git_setup autocommit
    - uses: ad-m/git-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
